export const ROUTES = {
  USERS: '/users',
  SESSIONS: '/sessions',
  ADDRESS: '/address',
  FILES: '/files',
  CANDIDATES: '/candidates',
  JOBS: '/jobs',
  CANDIDATEJOBS: '/candidate-jobs',
  AVAILABILITIES: '/availabilities',
  CANDIDATEAVAILABILITIES: '/candidate-availabilities',
  COURSETIME: '/course-time',
  CANDIDATECOURSETIME: '/candidate-course-time',
  PERSONALITIES: '/personalities',
  CANDIDATEPERSONALITIES: '/candidate-personalities',
  SKILLS: '/skills',
  CANDIDATESKILLS: '/candidate-skills',
  IDIOMS: '/idioms',
  CANDIDATEIDIOMS: '/candidate-idioms',
  VACANCIES: '/vacancies',
};
